name: Azure Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6  # Substitua pela versão mais recente do Terraform

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform  # Defina o diretório onde os arquivos .tf estão

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform  # Defina o diretório onde os arquivos .tf estão
